### PR TITLE
add: support for update collections

### PR DESCRIPTION
**Pull request by sashahilton00**
## Change Summary

add: support for update collections

fix: document update returns 200 not 201 code.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by sashahilton00** [comment]
do you want me to regenerate this from the updated spec before merging?

**Comment by kishorenc** [comment]
I presumed this was already generated after the changes in https://github.com/typesense/typesense-api-spec/pull/26 -- was it done before?

**Comment by sashahilton00** [comment]
It was, I didn't see the spec was out of date until after. I'm regenerating now, will squash and rebase

**Comment by sashahilton00** [comment]
@kishorenc done

**Review by kishorenc — APPROVED** [review]

**Pull request merged**
