### PR TITLE
Update to latest openapi.yml spec with support for filter_by when updating documents

### PR DESCRIPTION
**Pull request by sashahilton00**
## Change Summary

rebuilds the client using the latest API spec currently pending PR approval [#34](https://github.com/typesense/typesense-api-spec/pull/34)

This adds support for the `PATCH /collections/:collection_name/documents` endpoint, where `filter_by` can be used to filter and update multiple documents.

The unit tests have also been updated to reflect changes to the spec, please review for accuracy/expected behavoiur before merge.

One thing to note, I'm not sure if it's an issue with my OpenAPI generator or some nuance of OpenAPI itself, but when generating the new client, the `filter_by` parameter is wrapped in a `UpdateDocumentParameters` struct, which is wrapped in another struct, `UpdateDocumentParams` - this leads to the following ugly struct initialisation when using the new endpoint to pass the filter:

```golang
&api.UpdateDocumentsParams{
	UpdateDocumentsParameters: &struct {
		FilterBy *string `json:"filter_by,omitempty"`
	}{
		FilterBy: pointer.String(filter),
	},
}
```

given that this is a less than pleasant UX when one wishes to use it, this ugliness is contained within an unexported function, `updateDocuments` and called from the exported interface, such that the exported interface is:

```golang
Update(updateFields interface{}, filter string) (int, error)
```

If this is an unnecessary fix due to some sort of generator error on my behalf, let me know what needs to be changed on my side and I'll clean it up.

## PR Checklist

- [x] I have read and signed the [Contributor License Agreement](https://forms.gle/PZyiY5N2GDQU8GsV9).

### CODE REVIEW

**Comment by kishorenc** [comment]
@sashahilton00 

I forgot that to address this shortcoming of the generator creating those wrappers, we wrote a script to unwrap the objects manually before generating the code. See here: https://github.com/typesense/typesense-go/blob/e4ab9f73e8e5f3cd32871a8d1c3bba60fa023050/typesense/api/generator/main.go#L46

We could add code to do the same here as well.

**Comment by sashahilton00** [comment]
Ah, that makes sense, I didn't really look at the generator code, will refactor and squash.

**Comment by sashahilton00** [comment]
All done. The commit is a bit chunky due to needing to update the tests to accomodate the recent changes to the spec in addition to adding the functionality.

**Review by kishorenc — APPROVED** [review]
Thank you!

**Pull request merged**
